# Generated by Django 5.2.12 on 2026-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_planilha', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='P/N')),
                ('fabricante', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('unidade', models.CharField(max_length=20, verbose_name='Unidade')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('moeda', models.CharField(max_length=20, verbose_name='Moeda')),
                ('preco_fornecedor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Fornecedor')),
                ('unit_reais', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit (Reais)')),
                ('frete_na_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Frete na Compra')),
                ('ipi', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='IPI (%)')),
                ('icms', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ICMS (%)')),
                ('nome_fornecedor', models.CharField(max_length=100, verbose_name='Nome do Fornecedor')),
                ('estado_origem', models.CharField(max_length=5, verbose_name='Estado de Origem')),
                ('grupo_financeiro', models.CharField(max_length=50, verbose_name='Grupo Financeiro')),
                ('ncm', models.CharField(max_length=20, verbose_name='NCM')),
                ('data_ultima_cotacao', models.DateField(verbose_name='Data da Última Cotação')),
                ('lucro_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Lucro %')),
                ('iss_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ISS %')),
                ('pis_cofins_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PIS e COFINS %')),
                ('ir_csll_lp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IR e CSLL (LP) %')),
                ('ir_csll_lr', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IR e CSLL (LR) %')),
                ('mkp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='MKP')),
                ('custo_loc', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo LOC')),
                ('custo_mensal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo Mensal')),
                ('iss_loc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ISS loc')),
                ('pis_cofins_loc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PIS e COFINS LOC')),
                ('ir_csll_lp_loc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IR e CSLL (LP) LOC')),
                ('ir_csll_lr_loc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IR e CSLL (LR) LOC')),
                ('mkp_loc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='MKP LOC')),
            ],
        ),
    ]
