# Generated by Django 5.2.12 on 2026-03-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_empresa_id_alter_itemprojeto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estado_origem',
            field=models.CharField(max_length=100, verbose_name='Estado de Origem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modelo',
            field=models.CharField(max_length=500, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome_fornecedor',
            field=models.CharField(max_length=1000, verbose_name='Nome do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='part_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='P/N'),
        ),
    ]
