# Generated by Django 5.2.12 on 2026-03-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_projeto_manual', models.CharField(max_length=50, verbose_name='ID do Projeto')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('estado_obra', models.CharField(max_length=2, verbose_name='UF')),
                ('municipio_obra', models.CharField(max_length=100, verbose_name='Cidade')),
                ('empresa_executora', models.CharField(choices=[('EMIVE', 'EMIVE'), ('DIGITAL', 'DIGITAL'), ('CH', 'CH'), ('BMSi', 'BMSi')], max_length=20)),
                ('faturamento_servico', models.CharField(choices=[('MENSAL', 'Mensal Recorrente'), ('INSTALACAO', 'Instalação')], max_length=20)),
                ('tipo_projeto', models.CharField(default='Privado', max_length=10)),
                ('licitacao_publicada', models.BooleanField(default=False)),
                ('material_aplicado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
