# Generated by Django 5.2.12 on 2026-03-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('verde', 'OK'), ('amarelo', 'Aguardando Validação'), ('azul', 'Validado'), ('vermelho', 'Descontinuado')], default='verde', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Projeto finalizado'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='id_projeto_manual',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID do Projeto'),
        ),
    ]
