# Generated by Django 5.2.12 on 2026-03-26 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Unitário')),
                ('faturar_servico', models.BooleanField(default=False, verbose_name='Faturar como Serviço')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.projeto')),
            ],
            options={
                'unique_together': {('projeto', 'produto')},
            },
        ),
    ]
